# coding: utf-8

"""
    Continue Hub IDE API

    API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import json
import unittest

from openapi_client.models.get_assistant200_response import GetAssistant200Response
from openapi_client.models.list_assistants200_response_inner_config_result import (
    ListAssistants200ResponseInnerConfigResult,
)


class TestGetAssistant200Response(unittest.TestCase):
    """GetAssistant200Response unit tests"""

    def setUp(self) -> None:
        self.model = GetAssistant200Response(
            owner_slug="my-org",
            package_slug="review-bot",
            config_result=ListAssistants200ResponseInnerConfigResult(
                config={"models": []},
                config_load_interrupted=False,
            ),
        )

    def tearDown(self) -> None:
        pass

    def test_serialization_round_trip(self) -> None:
        """Serialized JSON must preserve required fields."""
        data = json.loads(self.model.model_dump_json())
        self.assertEqual(data["owner_slug"], "my-org")
        self.assertEqual(data["package_slug"], "review-bot")
        self.assertIsNotNone(data["config_result"])
        self.assertFalse(data["config_result"]["config_load_interrupted"])

    def test_deserialization(self) -> None:
        """A payload parsed back into the model must match the original."""
        payload = json.loads(self.model.model_dump_json())
        parsed = GetAssistant200Response.model_validate(payload)
        self.assertEqual(parsed.owner_slug, "my-org")
        self.assertEqual(parsed.package_slug, "review-bot")
        self.assertFalse(parsed.config_result.config_load_interrupted)

    def test_required_fields_are_enforced(self) -> None:
        """Missing required fields must raise a validation error, not silently pass."""
        with self.assertRaises(Exception):
            GetAssistant200Response(owner_slug="x")


if __name__ == "__main__":
    unittest.main()