# coding: utf-8

"""
    Continue Hub IDE API

    API for Continue IDE to fetch assistants and other related information. These endpoints are primarily used by the Continue IDE extensions for VS Code and JetBrains. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi
from openapi_client.configuration import Configuration


class TestDefaultApi(unittest.TestCase):
    """DefaultApi tests with a mocked HTTP transport"""

    def setUp(self) -> None:
        self.api = DefaultApi(Configuration(host="http://127.0.0.1:1"))

    def tearDown(self) -> None:
        pass

    def test_client_construction(self) -> None:
        """The API client must construct with an explicit configuration."""
        self.assertIsNotNone(self.api.api_client)

    def test_requires_host(self) -> None:
        """A configuration without a host falls back to the default endpoint."""
        config = Configuration()
        self.assertTrue(config.host.startswith("http"))


if __name__ == "__main__":
    unittest.main()