name: Issue assignment

on:
  issues:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@7bf9d82c77d45976224660b873fc83e60576c5aa # v2
        with:
          repo-token: ${{ github.token }}
          assignees: Patrick-Erichsen,tomasz-stefaniak,RomneyDa,tingwai,uinstinct
          numOfAssignee: 1
      # - name: "Add default labels"
      #   uses: actions-ecosystem/action-add-labels@18f1af5e3544586314bbe15c0273249c770b2daf
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: |
      #       "needs-triage"
